### ISSUE TITLE
dell_idrac_credentials.yaml

### ISSUE THREAD

**Issue by neffen37** [albertgranya/Home-Assistant-Dell-Server-Frontend#1]
hello I tried to use your super integration for my dell server under home assistant but I have a problem when I enter my identifiers I have a home assistant error when emptying the config

sorry for using google trad i am french ;)

![msedge_cX4Ai1IMyh](https://github.com/albertgranya/Home-Assistant-Dell-Server-Frontend/assets/29715586/1ab61c0d-b565-44be-a8dd-801d2bc4198c)
![msedge_kK6mcE6nk2](https://github.com/albertgranya/Home-Assistant-Dell-Server-Frontend/assets/29715586/4f1f358c-9978-4b63-9d99-465267d30cbf)
![msedge_Xd2B9eYdgA](https://github.com/albertgranya/Home-Assistant-Dell-Server-Frontend/assets/29715586/ea2aaddc-a4ba-4114-9f35-5093ce589694)

**Comment by albertgranya** [comment]
Hi, easy way is:
Sorry but secrets.yaml not shared....
in secrets.yaml file, is in same folder configuration.yaml,
put next keys values , with your idrack configuration

ServerIdracIP: 192.168.1.61
idrac_password: your idrack root password
idrac_user: root

- platform: template
  sensors:
    dell_idrac_password:
      value_template: !secret idrac_password
    dell_idrac_user:
      value_template: !secret idrac_user


This should work

**Comment by neffen37** [comment]
thank you I entered the passwords and the IP in each snmp scan and it works thank you.
I'm going to look into fan control.
